version = 1

[python]
version = "3.14"

[validation]
checks = ["ruff", "ruff-format", "mypy", "pytest", "pytest-coverage", "pre-commit"]

[coverage]
target = "wood"

[build]
python_package = true

[release]
semantic_release = true
